### ISSUE TITLE
Please add add info file for yourself

### ISSUE THREAD

**Issue by brrtha** [rick446/collab#26]
Please tell me a little bit about youself @sekharchittala.

- [x] Include your full name

- [x] Include your favorite food

**Comment by brrtha** [comment]
Hello ... my name is Bertha Renee Stanfill.

I love LOTS of food ... but if I had to eat food something everyday ... it would be sushi.

Thanks for asking @sekharchittala.

**Comment by sekharchittala** [comment]
Hi 

This is Sekhar Chittala

I love Biryani and when I have that I also walk a lot to be healthy

**Comment by brrtha** [comment]
Thank you!  closing this issue now.
